### PR TITLE
Start work on CI support

### PR DESCRIPTION
**Pull request by farski**

### CODE REVIEW

**Comment by pkarman** [comment]
@farski was is the status of this PR?

**Comment by farski** [comment]
I could probably spend time to figure it out, but I suspect @cavis could bang it out in a few minutes. I think it was just a simple Docker issue that I was running into that I didn't know how to debug.

**Comment by cavis** [comment]
After talking with Andrew yesterday ... we may want to just punt on these lambdas.

It's likely PRX/feeder.prx.org#291 will create a "modern" CI/CD deployed "lambda fixer".  And it will be generic enough that eventually, we'll move both the CMS audio/image lambdas to it, and retire these legacy functions.

**Comment by farski** [comment]
But all my hard work!

**Pull request closed without merging**
